### ISSUE TITLE
Android app successfully purchased CONSUMABLE items once - all items now "Not Available".

### ISSUE THREAD

**Issue by fiodhrid** [Fovea/cordova-plugin-purchase-demo#10]
the older version of the plugin had a method to set "consumed" on the CONSUMABLE products. I do not find any equivalent on the current Telerik version which I am using. Anyhow, my test account was able to purchase consumables one time. Now Android pops a notification that the products are "Not Available". Status of the products is "VALID".

Can I please have some help to fix this?

Thank you,

Phil T.

**Comment by Dhamu143** [comment]
can you please help me to solve the error inapp purchase in android ?

**Comment by j3k0** [comment]
Please report issues with the plugin here: https://github.com/j3k0/cordova-plugin-purchase/issues

Here is for issues with the demo application.
