### ISSUE TITLE
Error: Registry returned 404 for GET on https://registry.npmjs.org/org.apache.cordova.console

### ISSUE THREAD

**Issue by ron1010** [Fovea/cordova-plugin-purchase-demo#15]
trying  to follow the usage for Android, get up to:

cordova plugin add org.apache.cordova.console

and am getting:

Error: Registry returned 404 for GET on https://registry.npmjs.org/org.apache.cordova.console

Any ideas?

Ron.

**Comment by j3k0** [comment]
Indeed, apache / cordova has changed the name for their plugins. It's not cordova-plugin-console (same idea for the other plugins)

**Comment by j3k0** [comment]
Fixed.
