### ISSUE TITLE
Is there a code sample that handles an downloaded zip file from the app store?

### ISSUE THREAD

**Issue by halukkaramete** [Fovea/cordova-plugin-purchase-demo#16]
Hi, I am in dark as far as what to do about an incoming download which is initiated upon an in-app-purchase.

I need to unzip the file and mount the folders and the files that are in the zip content into appropriate locations. The download is not a single file unfortunately.  It's got 50 gif, 50 small mp3, and a bunch of html files. 

If this was PHP, I would have known what to do abut this but with JS & HTML, I am clueless. 

Is there a documentation that someone can lead me to please?

**Comment by j3k0** [comment]
My best clue would be to find a cordova plugin capable of unzipping stuff. Unzipping in JS might be possible but extremely slow, depending on the size of the file. It may even not be possible on smaller devices. This is an issue unrelated to this plugin (which only responsibility is to deliver the downloaded file, whatever it is).

**Comment by halukkaramete** [comment]
That makes sense. I was thinking along the same terms. Once this plug in hands in the dowloaded file, another plug in, should unzip it and save the file in the app folder properly. Since Objective C can do that, there should not be a problem. Thank you for the reply.
