### ISSUE TITLE
store.order(productid) does nothing

### ISSUE THREAD

**Issue by radoxFTW** [Fovea/cordova-plugin-purchase-demo#18]
Hello,

probably i'm doing something wrong but when I call store.order(productid) nothing happens. I expect Google Store pop up window that let me proceed with the purchase, am I wrong?

All other method calls are ok, store is initialized, product is registerd, considered not owned and it can be bought. Product is also listed in Google Play Store (infact i can get product price correctly).
Actually I am testing with a Android 8 HTC 10.

Any suggestion?

Thanks!

**Comment by j3k0** [comment]
It's been a while, did you figure this out?

**Comment by radoxFTW** [comment]
Yes, I did. I think that there was nothing wrong on the plugin but it was somehow my fault.

Thanks
