### ISSUE TITLE
possible error on renderIAP function

### ISSUE THREAD

**Issue by mrweix** [Fovea/cordova-plugin-purchase-demo#6]
in the file www/js/index.js   on line 285 it is 
          var elId = p.id.split(".")[3];

Checking the code myself, the buttons are not displayed...

I think it should rather be

var elId = p.id;

Can you confirm this?

**Comment by dpapesz** [comment]
Also 
on line 299    productId='" + p.id + "'   should be      data-productid='" + p.id + "' 
and on line 304 var pid = this.getAttribute("productId");   should be   var pid = this.getAttribute("data-productid");

**Comment by j3k0** [comment]
Fixed, made the code friendlier to different product-id formats.
