### ISSUE TITLE
Being asked iTune Store password every time open app

### ISSUE THREAD

**Issue by ngoclt** [Fovea/cordova-plugin-purchase-demo#8]
From what I checked in source code. The plugin try to restore the previous transactions every time we call store.refresh() method. 
If we don't call this method, the app can't fetch the IAP products (from my understanding). But by calling this method, app will ask user's iTune Store password for restoring process. Therefore, the popup keep showing up every time user open app. It's not really convenience  for user. 

Is there anyway that I can fetch product infos from App Store without calling store.refresh() method ? 

Thanks in advanced !

**Comment by j3k0** [comment]
It's not trying to restore purchases on startup. Only if you call `refresh()` twice. In order to load products when your in dev, the device needs to login to the `sandbox` server, that's why you see this popup often while you're in dev.
